#!/bin/bash
# ============================================================
# 浏览器环境恢复脚本（chrome-devtools-mcp 自愈）
# 用途：沙箱重置后，一条命令恢复真实浏览器能力
# 用法：bash /workspace/emallsoon/scripts/setup-browser.sh
#
# 背景知识（2026-08-30 实测）：
#   chrome-devtools-mcp（插件以 npx 启动）在 Linux 上寻找
#   /opt/google/chrome/chrome（stable 渠道标准位置）。
#   沙箱基础镜像自带完整 Chrome 二进制（~/.cache/puppeteer/，
#   镜像内置，重置后仍存活），但缺两样东西：
#     1. 系统库（libatk 等 X11 库，apt 装在系统层，重置即失）
#     2. /opt/google/chrome 路径（系统层，重置即失）
#   且沙箱以 root 运行、无显示器，Chrome 必须加
#   --no-sandbox --headless=new 才能启动。
#   解法：/opt/google/chrome/chrome 放一个包装脚本，
#   自动附加必需参数后转发给真实二进制。
#
# 浏览器配置文件（cookies/登录态）持久化：
#   chrome-devtools-mcp 的 profile 默认在
#   ~/.cache/chrome-devtools-mcp/chrome-profile（重置即失）。
#   本脚本将其符号链接到 /workspace/.browser-profile（持久），
#   重置后浏览器登录态/cookies 全部保留。
#
# 幂等设计：可重复执行，已就绪的步骤自动跳过。
# ============================================================
set -uo pipefail

PERSIST_PROFILE="/workspace/.browser-profile"
MCP_CACHE_DIR="/root/.cache/chrome-devtools-mcp"
MCP_PROFILE="$MCP_CACHE_DIR/chrome-profile"
PROXY="http://127.0.0.1:18080"

ok()   { echo "  ✅ $1"; }
warn() { echo "  ⚠️  $1"; }
fail() { echo "  ❌ $1"; }

echo "=========================================="
echo " 浏览器环境恢复（setup-browser）"
echo "=========================================="

# ---------- 1. 定位 Chrome 二进制 ----------
CHROME_REAL=$(ls -d /root/.cache/puppeteer/chrome/*/chrome-linux64/chrome 2>/dev/null | sort -V | tail -1)
if [ -z "$CHROME_REAL" ]; then
  fail "基础镜像中未找到 Chrome 二进制（~/.cache/puppeteer/chrome/）"
  echo "  备选恢复：cd /tmp && npx -y @puppeteer/browsers install chrome@stable"
  exit 1
fi
ok "Chrome 二进制: $CHROME_REAL"

# ---------- 2. 安装缺失系统库 ----------
if ldd "$CHROME_REAL" 2>/dev/null | grep -q "not found"; then
  echo "  [lib] 检测到缺失库，通过代理安装..."
  export http_proxy="$PROXY" https_proxy="$PROXY"
  apt-get update -qq 2>/dev/null
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libatk1.0-0 libatk-bridge2.0-0 libxcomposite1 libxdamage1 libatspi2.0-0 \
    >/dev/null 2>&1
  if ldd "$CHROME_REAL" 2>/dev/null | grep -q "not found"; then
    fail "库安装后仍有缺失，请手动执行: ldd $CHROME_REAL | grep 'not found'"
    exit 1
  fi
  ok "系统库已安装"
else
  ok "系统库完整，跳过安装"
fi

# ---------- 3. 安装 /opt/google/chrome 包装器 ----------
# MCP 只认 /opt/google/chrome/chrome 这个路径；包装脚本自动附加
# root/无显示器环境必需的启动参数 + 代理探测。
#
# 代理策略（2026-08-30 适配 AWS 吉隆坡出口，用户决定浏览器不走代理）：
#   1. privoxy 分流代理（18082）在线 → 走 18082（隧道场景保留）
#   2. SSH 隧道（1080）在线 → 全流量走隧道（Chrome 原生 socks5 远端 DNS）
#   3. 都不在线 → 直连（无代理）。当前出口在海外，Google/GitHub 直连均可达。
#
# ⚠️ 2026-08-30 踩坑存档（勿回退）：
#   a) 原方案的兜底分支是 --proxy-server=http://127.0.0.1:18080 +
#      --proxy-bypass-list="<-loopback>"。实测 "<-loopback>" 的语义是
#      移除 Chrome 默认的 loopback 绕过 → localhost 强制走代理 →
#      沙箱代理对回环目标返回 403 → 本地 dev/preview 服务器全部打不开。
#   b) --proxy-bypass-list 传非法值（如 *）会静默挂死 Chrome 网络栈，
#      表现为所有页面 Navigation timeout，且无任何控制台报错。
#   c) 本地测试用 127.0.0.1（IPv4）：astro preview 若只监听 [::1]，
#      Chrome 直连 127.0.0.1 会 ERR_CONNECTION_REFUSED，
#      启动 preview 时加 --host 0.0.0.0 可避免。
mkdir -p /opt/google/chrome
cat > /opt/google/chrome/chrome << WRAPPER
#!/bin/bash
# Auto-generated by setup-browser.sh — do not edit by hand
# 沙箱必需参数：root 无沙箱 / 无 GPU / 无显示器 / shm 限制
# 代理探测（18082 privoxy 分流 → 1080 SSH 隧道 → 直连无代理）
REAL="$CHROME_REAL"
if ss -tln 2>/dev/null | grep -q "127.0.0.1:18082"; then
  exec "\$REAL" --no-sandbox --disable-gpu --disable-dev-shm-usage --headless=new \\
    --proxy-server=http://127.0.0.1:18082 "\$@"
elif ss -tln 2>/dev/null | grep -q "127.0.0.1:1080"; then
  exec "\$REAL" --no-sandbox --disable-gpu --disable-dev-shm-usage --headless=new \\
    --proxy-server=socks5://127.0.0.1:1080 \\
    --host-resolver-rules="MAP * ~NOTFOUND, EXCLUDE 127.0.0.1" "\$@"
else
  exec "\$REAL" --no-sandbox --disable-gpu --disable-dev-shm-usage --headless=new "\$@"
fi
WRAPPER
chmod +x /opt/google/chrome/chrome
ok "包装器已安装: /opt/google/chrome/chrome（隧道在线则分流，否则直连无代理）"

# ---------- 3.5 SSH 隧道 + privoxy（Google 访问能力） ----------
TUNNEL_DIR="/workspace/.tunnel"
if [ -f "$TUNNEL_DIR/start-tunnel.sh" ]; then
  # 安装依赖（privoxy 分流代理 + sshpass 密码登录）
  NEED_INSTALL=0
  command -v privoxy >/dev/null 2>&1 || NEED_INSTALL=1
  command -v sshpass >/dev/null 2>&1 || NEED_INSTALL=1
  if [ "$NEED_INSTALL" = "1" ]; then
    echo "  [tunnel] 安装 privoxy + sshpass ..."
    export http_proxy="$PROXY" https_proxy="$PROXY"
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      privoxy sshpass >/dev/null 2>&1
  fi
  # 恢复 privoxy 配置（若持久区丢失则从仓库模板重建）
  if [ ! -f "$TUNNEL_DIR/privoxy.conf" ] && [ -f "$(dirname "$0")/privoxy-emallsoon.conf" ]; then
    mkdir -p "$TUNNEL_DIR"
    cp "$(dirname "$0")/privoxy-emallsoon.conf" "$TUNNEL_DIR/privoxy.conf"
    ok "已从仓库模板恢复 privoxy.conf"
  fi
  # 已在运行则跳过，否则后台启动（含自动重连）
  if ss -tln 2>/dev/null | grep -q "127.0.0.1:18082"; then
    ok "隧道 + privoxy 已在运行（18082）"
  else
    nohup bash "$TUNNEL_DIR/start-tunnel.sh" > /data/user/work/tunnel-start.log 2>&1 &
    sleep 8
    if ss -tln 2>/dev/null | grep -q "127.0.0.1:18082"; then
      ok "隧道 + privoxy 已启动（Google 可访问）"
    else
      warn "隧道启动中或失败，详见 /data/user/work/tunnel-start.log（不影响 Bing/emallsoon 验证）"
    fi
  fi
else
  warn "无 /workspace/.tunnel/start-tunnel.sh → 浏览器直连模式（无代理；当前海外出口 Google/GitHub 直连可达）"
fi

# ---------- 4. 浏览器配置文件持久化 ----------
if pgrep -f "chrome.*user-data-dir" >/dev/null 2>&1; then
  warn "Chrome 正在运行，跳过 profile 迁移（下次无浏览器运行时执行）"
else
  mkdir -p "$PERSIST_PROFILE"
  mkdir -p "$MCP_CACHE_DIR"
  if [ -d "$MCP_PROFILE" ] && [ ! -L "$MCP_PROFILE" ]; then
    # 已存在真实目录（未链接）→ 首次迁移：内容并入持久目录后替换为符号链接
    cp -a "$MCP_PROFILE/." "$PERSIST_PROFILE/" 2>/dev/null
    rm -rf "$MCP_PROFILE"
    ok "已将现有 profile 迁移到 $PERSIST_PROFILE"
  fi
  ln -sfn "$PERSIST_PROFILE" "$MCP_PROFILE"
  ok "profile 持久化: $MCP_PROFILE → $PERSIST_PROFILE"
fi

# ---------- 5. 验证 ----------
VERSION=$(/opt/google/chrome/chrome --version 2>/dev/null)
if [ -n "$VERSION" ]; then
  ok "浏览器验证通过: $VERSION"
else
  fail "浏览器启动失败，请检查上方日志"
  exit 1
fi

echo "------------------------------------------"
echo " 完成：真实浏览器（Chrome DevTools MCP）可用"
echo " 截图工具：bash scripts/browser-shot.sh <url> <out.png>"
echo "------------------------------------------"
